version: "3.3"

services:

  contracts-packages:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: contracts-packages

  contracts:
    container_name: contracts
    image: contracts-packages:latest
    command: tail -F anything
    volumes:
      - ./.env:/home/node/contracts/contracts/.env
      - ./contracts:/home/node/contracts/contracts
      - ./scripts:/home/node/contracts/scripts
      - ./artifacts:/home/node/contracts/artifacts
      - ./typechain-types:/home/node/contracts/typechain-types
    environment:
      MM_MNEMONIC: "${MM_MNEMONIC}"
      MM_PRIVATEKEY: "${MM_PRIVATEKEY}"

      RINKEBY_RPC_URL: "${RINKEBY_RPC_URL}"
      ROPSTEN_RPC_URL: "${ROPSTEN_RPC_URL}"
      POLYGON_RPC_URL: "${POLYGON_RPC_URL}"
      MUMBAI_RPC_URL: "${MUMBAI_RPC_URL}"
      ROPSTEN_PRIVATE_KEY: "${ROPSTEN_PRIVATE_KEY}"
      REPORT_GAS: "${REPORT_GAS}"
      ETHERSCAN_API_KEY: "${ETHERSCAN_API_KEY}"

      BINANCE_RPC_URL: "${BINANCE_RPC_URL}"
      BESU_RPC_URL: "${BESU_RPC_URL}"

  besu-test:
    container_name: besu-test
    restart: "on-failure"
    image: hyperledger/besu:latest
    environment:
      BESU_GENESIS_FILE: /var/lib/besu/gen-besu.json
      BESU_DATA_PATH: /var/lib/besu
      BESU_HOST_ALLOWLIST: "*"
      BESU_RPC_WS_ENABLED: "true"
      BESU_RPC_WS_HOST: 0.0.0.0
      BESU_RPC_HTTP_HOST: 0.0.0.0
      BESU_RPC_HTTP_ENABLED: "true"
      BESU_RPC_HTTP_CORS_ORIGINS: "*"
      BESU_MINER_ENABLED: "true"
      BESU_MINER_COINBASE: fe3b557e8fb62b89f4916b721be55ceb828dbd73
    volumes:
      - $PWD/besu:/var/lib/besu
      - $PWD/gen-besu.json:/var/lib/besu/gen-besu.json
    ports:
      - "${JSON_RPC_PORT}:8545"
      - "${WS_PORT}:8546"
      - "${GRAPHQL_PORT}:8547"
      - "${P2P_PORT}:30303"

  besu-explorer:
    container_name: besu-explorer
    restart: "on-failure"
    image: alethio/ethereum-lite-explorer
    environment:
      APP_NODE_URL: "http://127.0.0.1:${JSON_RPC_PORT}"
    ports:
      - 8080:80
    depends_on:
      - besu-test


