
name: Manual Publish (NPM) --force
on:
  workflow_dispatch:

jobs:
  user-publish:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALL
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          always-auth: true
          registry-url: https://registry.npmjs.org/

      - name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./.npmrc

      - name: Authenticate NPM Registry & Configure Git User
        run: |
          echo "save-exact=true" > .npmrc
          echo "package-lock=false" >> .npmrc
          echo "legacy-peer-deps=true" >> .npmrc
          git update-index --assume-unchanged .npmrc
          echo "@gemunion:registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Packages npm i
        run: npm i
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          JSON_RPC_ADDR_ETHEREUM: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GORLY: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE_TEST: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_POLYGON: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_MUMBAI: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BESU: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GEMUNION: "http://127.0.0.1:8545/"

      - name: Bootstrap Packages
        run: npm run bootstrap && npm run build
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          JSON_RPC_ADDR_ETHEREUM: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GORLY: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE_TEST: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_POLYGON: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_MUMBAI: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BESU: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GEMUNION: "http://127.0.0.1:8545/"

      - name: Publish NPM with lerna
        run: npm run release:publish:npm -- --force-publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          MNEMONIC: ${{ secrets.MNEMONIC }}
          JSON_RPC_ADDR_ETHEREUM: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GORLY: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BINANCE_TEST: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_POLYGON: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_MUMBAI: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_BESU: "http://127.0.0.1:8545/"
          JSON_RPC_ADDR_GEMUNION: "http://127.0.0.1:8545/"
