
name: Manual release Publish
on:
  workflow_dispatch:

jobs:
  user-publish:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALL
      - uses: actions/checkout@v3

      - name: Authenticate Registry & Configure Git User
        run: |
          echo "@gemunion:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUBTOKEN" >> .npmrc
          git update-index --assume-unchanged .npmrc
          npx npm-cli-login -u $GITHUBUSER -p $GITHUBTOKEN -e $GITHUBEMAIL -r https://npm.pkg.github.com -s @gemunion --config-path="./"
          git config --global user.name '@gemunion'
          git config --global user.email $GITHUBEMAIL
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUBUSER: ${{ secrets.GITHUBUSER }}
          GITHUBEMAIL: ${{ secrets.GITHUBEMAIL }}

      - name: Authenticate check via npm
        run: npm whoami --registry=https://npm.pkg.github.com/

      - name: Install Packages npm i
        run: npm i
        env:
          MM_PRIVATEKEY: ${{ secrets.MM_PRIVATEKEY }}
          MM_MNEMONIC: ${{ secrets.MM_MNEMONIC }}
          JSON_RPC_ADDR_BINANCE: "https://bsc-dataseed.binance.org/"
          JSON_RPC_ADDR_BINANCE_TEST: "https://data-seed-prebsc-1-s1.binance.org:8545"
          JSON_RPC_ADDR_POLYGON: ${{ secrets.JSON_RPC_ADDR_POLYGON }}
          JSON_RPC_ADDR_MUMBAI: ${{ secrets.JSON_RPC_ADDR_MUMBAI }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          JSON_RPC_ADDR_BESU: ${{ secrets.JSON_RPC_ADDR_BESU }}

      - name: Bootstrap Packages
        run: npm run bootstrap && npm run build
        env:
          MM_PRIVATEKEY: ${{ secrets.MM_PRIVATEKEY }}
          MM_MNEMONIC: ${{ secrets.MM_MNEMONIC }}
          JSON_RPC_ADDR_BINANCE: "https://bsc-dataseed.binance.org/"
          JSON_RPC_ADDR_BINANCE_TEST: "https://data-seed-prebsc-1-s1.binance.org:8545"
          JSON_RPC_ADDR_POLYGON: ${{ secrets.JSON_RPC_ADDR_POLYGON }}
          JSON_RPC_ADDR_MUMBAI: ${{ secrets.JSON_RPC_ADDR_MUMBAI }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          JSON_RPC_ADDR_BESU: ${{ secrets.JSON_RPC_ADDR_BESU }}

      - name: What changed
        run: lerna changed
        id: lerna_changed
        continue-on-error: true

      - name: Version & Publish by lerna
        run: lerna version patch --yes --ignore-scripts && npm run release:publish
        if: steps.lerna_changed.outcome == 'success'
        env:
          MM_PRIVATEKEY: ${{ secrets.MM_PRIVATEKEY }}
          MM_MNEMONIC: ${{ secrets.MM_MNEMONIC }}
          JSON_RPC_ADDR_BINANCE: "https://bsc-dataseed.binance.org/"
          JSON_RPC_ADDR_BINANCE_TEST: "https://data-seed-prebsc-1-s1.binance.org:8545"
          JSON_RPC_ADDR_POLYGON: ${{ secrets.JSON_RPC_ADDR_POLYGON }}
          JSON_RPC_ADDR_MUMBAI: ${{ secrets.JSON_RPC_ADDR_MUMBAI }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          JSON_RPC_ADDR_BESU: ${{ secrets.JSON_RPC_ADDR_BESU }}

