
name: Manual release Publish
on:
  workflow_dispatch:

jobs:
  user-publish:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # BEGIN INSTALL
      - uses: actions/checkout@v2

      - name: Authenticate Registry & Configure Git User
        run: |
          echo "@gemunion:registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$GITHUBTOKEN" >> .npmrc
          git update-index --assume-unchanged .npmrc
          npx npm-cli-login -u $GITHUBUSER -p $GITHUBTOKEN -e $GITHUBEMAIL -r https://npm.pkg.github.com -s @gemunion --config-path="./"
          git config --global user.name '@gemunion'
          git config --global user.email $GITHUBEMAIL
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
          GITHUBUSER: ${{ secrets.GITHUBUSER }}
          GITHUBEMAIL: ${{ secrets.GITHUBEMAIL }}

      - name: Authenticate check via npm
        run: npm whoami --registry=https://npm.pkg.github.com/

      - name: Install Packages npm i
        run: npm i
        env:
          MM_PRIVATEKEY: ${{ secrets.MM_PRIVATEKEY }}
          MM_MNEMONIC: ${{ secrets.MM_MNEMONIC }}
          RPC_URL_BINANCE: ${{ secrets.RPC_URL_BINANCE }}
          ALCHEMY_API_KEY_RINKEBY: ${{ secrets.ALCHEMY_API_KEY_RINKEBY }}
          ALCHEMY_API_KEY_ROPSTEN: ${{ secrets.ALCHEMY_API_KEY_ROPSTEN }}
          ALCHEMY_API_KEY_POLYGON: ${{ secrets.ALCHEMY_API_KEY_POLYGON }}
          ALCHEMY_API_KEY_MUMBAI: ${{ secrets.ALCHEMY_API_KEY_MUMBAI }}
          ROPSTEN_PRIVATE_KEY: ${{ secrets.ROPSTEN_PRIVATE_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}

#      - name: Build Packages
#        run: env && npm run build
#        env:
#          MM_PRIVATEKEY: ${{ secrets.MM_PRIVATEKEY }}
#          MM_MNEMONIC: ${{ secrets.MM_MNEMONIC }}
#          RPC_URL_BINANCE: ${{ secrets.RPC_URL_BINANCE }}

      - name: Version by NPM
        run: npm version patch -m "[Manual release] [skip ci] %s"

      - name: Publish by NPM
        run: npm publish
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

      - name: Git push
        run: git push --no-verify && git push --tags --no-verify
        env:
          GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}

